### ISSUE TITLE
Incorrect action reference

### ISSUE THREAD

**Issue by SarvagyaVaish** [Farama-Foundation/gymnasium-env-template#3]
https://github.com/Farama-Foundation/gymnasium-env-template/blob/59d5aede3518de9fc33fa41208811230a89becc5/template/%7B%7Benvironment_name%7D%7D/envs/grid_world.py#L95

To use the `_action_to_direction` dict, we need to first convert the numerical action (0, 1, 2, 3) to an Enum. I think the correct statement is the following: 
```
direction = self._action_to_direction[Actions(action)]
```

Without that, I get a KeyError. 
```
  ... truncated stacktrace ...
  File "... /gymnasium_env/envs/grid_world.py", line 95, in step
    direction = self._action_to_direction[action]
KeyError: 3
```

**Comment by SarvagyaVaish** [comment]
If you agree, happy to create a quick PR with the fix :)

**Comment by pseudo-rnd-thoughts** [comment]
Yes, that would be great

**Comment by SarvagyaVaish** [comment]
@pseudo-rnd-thoughts PR created :) #4
